### ISSUE TITLE
2024 Comprehensive Update ⏳ 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-nextjs#2]
@LuchoTurtle I explored `Next.js` https://nextjs.org/ as part of a previous project (2021) ⏳ 
looks like we might be needing a quick start for the framework again.  🏦 

Wanna pick this up and expand it to the level of: https://github.com/dwyl/learn-tailwind ? 🧑‍💻 💭

**Comment by LuchoTurtle** [comment]
I'll add some personal insights and run through a personal demo and update it, sure 👌

**Comment by nelsonic** [comment]
https://nextjs.org/learn
